# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Alex Ungurianu
tagline:          'A Jekyll theme'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              http://ungurianu.com
baseurl:          /

author:
  name:           'Alex Ungurianu'
  url:            https://twitter.com/AlexUCodes

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/a-ungurianu/a-ungurianu.github.io
