# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Alex U.
tagline:          'Lost in CS'
description:      'Words on a screen...'
url:              https://ungurianu.com
baseurl:          '/'

author:
  name:           'Alex Ungurianu'
  url:            https://twitter.com/AlexUCodes

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/a-ungurianu/a-ungurianu.github.io
